/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//import randint;
package utspemvis;
//import java

import static java.util.stream.IntStream.range;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class UTS extends javax.swing.JFrame {

    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bMain = new javax.swing.JButton();
        cbPilih = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPlayer = new javax.swing.JTextField();
        tfKomputer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 153));

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        bMain.setText("MULAI");
        bMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMainActionPerformed(evt);
            }
        });
        jPanel2.add(bMain, java.awt.BorderLayout.PAGE_END);

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIIH", "Kertas", "Batu", "Gunting" }));
        cbPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihActionPerformed(evt);
            }
        });
        jPanel2.add(cbPilih, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("-----------");
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jLabel3.setText("-----------");
        jPanel2.add(jLabel3, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setText("SELAMAT BERMAIN");

        tfPlayer.setEditable(false);
        tfPlayer.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tfPlayer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPlayer.setText("0");
        tfPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlayerActionPerformed(evt);
            }
        });

        tfKomputer.setEditable(false);
        tfKomputer.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tfKomputer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKomputer.setText("0");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel4.setText("KOMPUTER");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel5.setText("PLAYER");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(tfPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMainActionPerformed
        // TODO add your handling code here:
        
        int pilih = cbPilih.getSelectedIndex();
//        int komputer = randint(1);
        int player = 0;
        int komputer1 = 0;
        int komputer = 0;
        while (komputer < 3){
            komputer +=1;
            
            if(pilih == 1 && komputer == 2){
                JOptionPane.showMessageDialog(this,  "Anda Menang !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                player++;
                tfPlayer.setText(Integer.toString(player));
                break; 
            }else if(pilih == 2 && komputer == 3){
                JOptionPane.showMessageDialog(this,  "Anda Menang !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                player++;
                tfPlayer.setText(Integer.toString(player));
                break;
            }else if (pilih == 3 && komputer == 1){
                JOptionPane.showMessageDialog(this,  "Anda Menang !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                player++;
                tfPlayer.setText(Integer.toString(player));
                break;
            }else if (pilih == 1 && komputer == 3){
                JOptionPane.showMessageDialog(this,  "Anda Kalah !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                komputer1++;
                tfPlayer.setText(Integer.toString(komputer1));
                break;
            }else if (pilih == 2 && komputer == 1){
                JOptionPane.showMessageDialog(this,  "Anda Kalah !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                komputer1++;
                tfPlayer.setText(Integer.toString(komputer1));
                break;
            }else if(pilih == 3 && komputer == 2){
                JOptionPane.showMessageDialog(this,  "Anda Kalah !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                komputer1++;
                tfPlayer.setText(Integer.toString(komputer1));
                break;
            }else if(pilih == komputer){
                JOptionPane.showMessageDialog(this,  "Imbang !!! ", "Pesan", JOptionPane.PLAIN_MESSAGE);
                break;
            }else{
                JOptionPane.showMessageDialog(this,  "KAMU BELUM MEMILIH !!! ", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        cbPilih.setSelectedIndex(0);
    }//GEN-LAST:event_bMainActionPerformed

    private void cbPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPilihActionPerformed

    private void tfPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMain;
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfKomputer;
    private javax.swing.JTextField tfPlayer;
    // End of variables declaration//GEN-END:variables

    private int randint(int i0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
